DROP TABLE B_IM_CHAT CASCADE CONSTRAINTS
/
DROP TABLE B_IM_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_IM_RELATION CASCADE CONSTRAINTS
/
DROP TABLE B_IM_RECENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_IM_CHAT
/
DROP SEQUENCE SQ_B_IM_MESSAGE
/
DROP SEQUENCE SQ_B_IM_RELATION
/
DROP SEQUENCE SQ_B_IM_RECENT
/