CREATE TABLE B_SOCIALSERVICES_USER
(
	ID INT NOT NULL IDENTITY (1, 1),
	LOGIN VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NULL,
	LAST_NAME VARCHAR(100) NULL,
	EMAIL VARCHAR(100) NULL,
	PERSONAL_PHOTO INT NULL,
	EXTERNAL_AUTH_ID VARCHAR(100) NOT NULL,
	USER_ID INT NOT NULL,
	XML_ID VARCHAR(100) NOT NULL,
	CAN_DELETE CHAR(1) NOT NULL,
	PERSONAL_WWW VARCHAR(100) NULL,
	PERMISSIONS VARCHAR(555) NULL,
	OATOKEN VARCHAR(250) NULL,
	OASECRET VARCHAR(250) NULL,
	REFRESH_TOKEN VARCHAR(250) NULL,
	SEND_ACTIVITY CHAR(1) NULL,
	SITE_ID VARCHAR(50) NULL,

)
GO
ALTER TABLE B_SOCIALSERVICES_USER ADD CONSTRAINT PK_B_SOCIALSERVICES_USER PRIMARY KEY (ID)
GO
ALTER TABLE B_SOCIALSERVICES_USER ADD CONSTRAINT DF_B_SOCIALSERVICES_USER_CAN_DELETE DEFAULT 'Y' FOR CAN_DELETE
GO
ALTER TABLE B_SOCIALSERVICES_USER ADD CONSTRAINT DF_B_SOCIALSERVICES_USER_SEND_ACTIVITY DEFAULT 'Y' FOR SEND_ACTIVITY
GO
CREATE UNIQUE INDEX IX_B_SOCIALSERVICES_USER ON B_SOCIALSERVICES_USER(XML_ID, EXTERNAL_AUTH_ID)
GO

CREATE TABLE B_SOCIALSERVICES_MESSAGE (
	ID INT NOT NULL IDENTITY (1, 1),
	USER_ID INT NOT NULL,
	SOCSERV_USER_ID INT NOT NULL,
	PROVIDER VARCHAR(100) NOT NULL,
	MESSAGE VARCHAR(1000) NULL,
	INSERT_DATE DATETIME NULL,
	SUCCES_SENT CHAR(1) NOT NULL CONSTRAINT DF_B_SOCIALSERVICES_MESSAGE_SUCCES_SENT DEFAULT 'N'
)
GO
ALTER TABLE B_SOCIALSERVICES_MESSAGE ADD CONSTRAINT PK_B_SOCIALSERVICES_MESSAGE PRIMARY KEY (ID)
GO