<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Welcome To Intranet Portal");
$APPLICATION->SetPageProperty("NOT_SHOW_NAV_CHAIN", "Y");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:desktop",
	"",
	Array(
		"ID" => "mainpage_#SITE_ID#",
		"CAN_EDIT" => "N",
		"COLUMNS" => "3",
		"COLUMN_WIDTH_0" => "260px",
		"COLUMN_WIDTH_1" => "",
		"COLUMN_WIDTH_2" => "260px",
		"G_ADV_TYPE" => "INFO",
		"GADGETS" => Array("ALL"),
		"G_VIDEO_IBLOCK_TYPE"=>"services",
		"G_VIDEO_IBLOCK_ID"=>"#VIDEO_IBLOCK_ID#",
		"G_VIDEO_PATH_TO_FILE"=>"#VIDEO_PATH_TO_FILE_ID#",
		"G_VIDEO_DURATION"=>"#VIDEO_DURATION_ID#",
		"G_VIDEO_SECTION_ID"=>"#VIDEO_SECTION_ID#",
		"G_VIDEO_ELEMENT_ID"=>"#VIDEO_ELEMENT_ID#",
		"G_VIDEO_WIDTH"=>"400",
		"G_VIDEO_HEIGHT"=>"300",
		"G_VIDEO_CACHE_TYPE"=>"A",
		"G_VIDEO_LIST_URL"=>"#SITE_DIR#about/media.php",
		"G_VIDEO_CACHE_TIME"=>"3600",
		"G_VOTE_CHANNEL_SID"=>"#SYMBOLIC_NAME_VOTE#",
		"G_VOTE_CACHE_TYPE"=>"A",
		"G_VOTE_CACHE_TIME"=>"3600",
		"G_VOTE_LIST_URL" => "#SITE_DIR#services/votes.php",
		"G_BIRTHDAY_STRUCTURE_PAGE"=>"structure.php",
		"G_BIRTHDAY_PM_URL"=>"#SITE_DIR#company/personal/messages/chat/#USER_ID#/",
		"G_BIRTHDAY_SHOW_YEAR"=>"M",
		"G_BIRTHDAY_USER_PROPERTY"=>Array("0"=>"PERSONAL_PHONE", "1"=>"PERSONAL_MOBILE", "2"=>"UF_DEPARTMENT", "3"=>"", ),
		"G_BIRTHDAY_LIST_URL"=>"#SITE_DIR#company/birthdays.php",
		"G_LIFE_IBLOCK_TYPE"=>"news",
		"G_LIFE_IBLOCK_ID"=>"#OUR_LIFE_IBLOCK_ID#",
		"G_LIFE_DETAIL_URL"=>"#SITE_DIR#about/life.php?ID=#ELEMENT_ID#",
		"G_LIFE_CACHE_TYPE"=>"A",
		"G_LIFE_CACHE_TIME"=>"3600",
		"G_LIFE_LIST_URL"=>"#SITE_DIR#about/life.php",
		"G_OFFICIAL_IBLOCK_TYPE"=>"news",
		"G_OFFICIAL_IBLOCK_ID"=>"#OFFICIAL_NEWS_IBLOCK_ID#",
		"G_OFFICIAL_DETAIL_URL"=>"#SITE_DIR#about/official.php?ID=#ELEMENT_ID#",
		"G_OFFICIAL_CACHE_TYPE"=>"A",
		"G_OFFICIAL_CACHE_TIME"=>"3600",
		"G_OFFICIAL_LIST_URL"=>"#SITE_DIR#about/",
		"G_SHARED_DOCS_IBLOCK_TYPE"=>"library",
		"G_SHARED_DOCS_IBLOCK_ID"=>"#SHARED_FILES_IBLOCK_ID#",
		"G_SHARED_DOCS_DETAIL_URL"=>"#SITE_DIR#docs/shared/element/view/#ELEMENT_ID#/",
		"G_SHARED_DOCS_CACHE_TYPE"=>"A",
		"G_SHARED_DOCS_CACHE_TIME"=>"3600",
		"G_SHARED_DOCS_LIST_URL"=>"#SITE_DIR#docs/",
		"G_COMPANY_CALENDAR_IBLOCK_TYPE"=>"events",
		"G_COMPANY_CALENDAR_IBLOCK_ID"=>"#CALENDAR_COMPANY_IBLOCK_ID#",
		"G_COMPANY_CALENDAR_DETAIL_URL"=>"#SITE_DIR#about/calendar.php",
		"G_COMPANY_CALENDAR_CACHE_TIME"=>"3600000",
		"G_PHOTOS_IBLOCK_TYPE"=>"photos",
		"G_PHOTOS_IBLOCK_ID"=>"#PHOTO_COMPANY_IBLOCK_ID#",
		"G_PHOTOS_DETAIL_URL"=>"#SITE_DIR#about/gallery/#SECTION_ID#/#ELEMENT_ID#/",
		"G_PHOTOS_DETAIL_SLIDE_SHOW_URL"=>"#SITE_DIR#about/gallery/#SECTION_ID#/#ELEMENT_ID#/slide_show/",
		"G_PHOTOS_CACHE_TYPE"=>"A",
		"G_PHOTOS_CACHE_TIME"=>"3600000",
		"G_PHOTOS_LIST_URL"=>"#SITE_DIR#about/gallery/",
		"G_WORKGROUPS_GROUP_VAR"=>"group_id",
		"G_WORKGROUPS_PATH_TO_GROUP"=>"#SITE_DIR#workgroups/group/#group_id#/",
		"G_WORKGROUPS_PATH_TO_GROUP_SEARCH"=>"#SITE_DIR#workgroups/",
		"G_WORKGROUPS_CACHE_TIME"=>"180",
		"G_BLOG_PATH_TO_BLOG"=>"#SITE_DIR#company/personal/user/#user_id#/blog/",
		"G_BLOG_PATH_TO_POST"=>"#SITE_DIR#company/personal/user/#user_id#/blog/#post_id#/",
		"G_BLOG_PATH_TO_GROUP_BLOG_POST"=>"#SITE_DIR#workgroups/group/#group_id#/blog/#post_id#/",
		"G_BLOG_PATH_TO_USER"=>"#SITE_DIR#company/personal/user/#user_id#/",
		"G_BLOG_CACHE_TYPE"=>"A",
		"G_BLOG_CACHE_TIME"=>"180",
		"G_FORUM_FID"=>Array("#GENERAL_FORUM_ID#"),
		"G_FORUM_SORT_BY"=>"LAST_POST_DATE",
		"G_FORUM_SORT_ORDER"=>"DESC",
		"G_FORUM_URL_TEMPLATES_MESSAGE"=>"#SITE_DIR#community/forum/messages/forum#FID#/topic#TID#/message#MID#/",
		"G_FORUM_CACHE_TYPE"=>"A",
		"G_FORUM_CACHE_TIME"=>"180",
		"G_TASKS_IBLOCK_ID"=>"#TASKS_IBLOCK_ID#",
		"G_TASKS_PATH_TO_GROUP_TASKS"=>"#SITE_DIR#workgroups/group/#group_id#/tasks/",
		"G_TASKS_PATH_TO_GROUP_TASKS_TASK"=>"#SITE_DIR#workgroups/group/#group_id#/tasks/task/#action#/#task_id#/",
		"G_TASKS_PATH_TO_USER_TASKS"=>"#SITE_DIR#company/personal/user/#user_id#/tasks/",
		"G_TASKS_PATH_TO_USER_TASKS_TASK"=>"#SITE_DIR#company/personal/user/#user_id#/tasks/task/#action#/#task_id#/",
		"G_CALENDAR_IBLOCK_TYPE"=>"events",
		"G_CALENDAR_IBLOCK_ID"=>"#CALENDAR_USERS_IBLOCK_ID#",
		"G_CALENDAR_DETAIL_URL"=>"#SITE_DIR#company/personal/user/#user_id#/calendar/",
		"G_CALENDAR_CACHE_TYPE"=>"N",
		"G_CALENDAR_CACHE_TIME"=>"3600000",
		"G_HONOUR_LIST_URL" => "#SITE_DIR#company/leaders.php",
		"G_NEW_EMPLOYEES_LIST_URL" => "#SITE_DIR#company/events.php",
		"DATE_TIME_FORMAT" => "F j, Y h:i a",
		"DATE_FORMAT" => "F j, Y",
		"DATE_FORMAT_NO_YEAR" => "F j",
		"G_LIFE_ACTIVE_DATE_FORMAT" => "F j, Y",
		"G_OFFICIAL_ACTIVE_DATE_FORMAT" => "F j, Y",
		"GU_BLOG_DATE_TIME_FORMAT" => "F j, Y h:i a",
		"GU_FORUM_DATE_TIME_FORMAT" => "F j, Y h:i a",
		"GU_WORKGROUPS_DATE_TIME_FORMAT" => "F j, Y",
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>