CREATE TABLE b_crm_lead
(
  ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
  DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
  DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
  CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
  MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  OPENED CHAR(1) DEFAULT 'N',
  COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
  CONTACT_ID INT (18) UNSIGNED DEFAULT NULL,  
  STATUS_ID VARCHAR (50) DEFAULT NULL,
  STATUS_DESCRIPTION TEXT DEFAULT NULL,
  PRODUCT_ID VARCHAR (50) DEFAULT NULL,
  OPPORTUNITY DECIMAL(18,2) DEFAULT NULL,
  CURRENCY_ID VARCHAR (50) DEFAULT NULL,
  OPPORTUNITY_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
  ACCOUNT_CURRENCY_ID VARCHAR (50) DEFAULT NULL,
  SOURCE_ID VARCHAR (50) DEFAULT NULL,
  SOURCE_DESCRIPTION TEXT DEFAULT NULL,
  TITLE VARCHAR (255) DEFAULT NULL,
  FULL_NAME VARCHAR (100) DEFAULT NULL,
  NAME VARCHAR (50) DEFAULT NULL,
  LAST_NAME VARCHAR (50) DEFAULT NULL,
  SECOND_NAME VARCHAR (50) DEFAULT NULL,
  COMPANY_TITLE VARCHAR (255) DEFAULT NULL,
  POST VARCHAR (255) DEFAULT NULL,
  ADDRESS TEXT DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  EXCH_RATE DECIMAL(18,2) DEFAULT 1,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  PRIMARY KEY (ID),
  KEY IX_LEAD_FULL_NAME (FULL_NAME)
);

CREATE TABLE b_crm_deal
(
  ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
  DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
  DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
  CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
  MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  OPENED CHAR(1) DEFAULT 'N',
  LEAD_ID INT (18) DEFAULT NULL,
  COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
  CONTACT_ID INT (18) UNSIGNED DEFAULT NULL,
  TITLE VARCHAR (255) DEFAULT NULL,
  PRODUCT_ID VARCHAR (50) DEFAULT NULL,
  STAGE_ID VARCHAR (50) DEFAULT NULL,
  CLOSED CHAR (1) DEFAULT 'N',
  TYPE_ID VARCHAR (50) DEFAULT NULL,
  OPPORTUNITY DECIMAL(18,2) DEFAULT NULL,
  CURRENCY_ID VARCHAR (50) DEFAULT NULL,
  OPPORTUNITY_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
  ACCOUNT_CURRENCY_ID VARCHAR (50) DEFAULT NULL,
  PROBABILITY TINYINT (3) DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  BEGINDATE DATETIME DEFAULT NULL,
  CLOSEDATE DATETIME DEFAULT NULL,
  EVENT_DATE DATETIME NULL,
  EVENT_ID varchar(50) NULL,
  EVENT_DESCRIPTION text NULL,
  EXCH_RATE DECIMAL(18,2) DEFAULT 1,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  ADDITIONAL_INFO TEXT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE b_crm_contact
(
  ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
  DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
  DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
  CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
  MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  OPENED CHAR(1) DEFAULT 'N',
  COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
  SOURCE_ID VARCHAR (50) DEFAULT NULL,
  SOURCE_DESCRIPTION TEXT DEFAULT NULL,
  FULL_NAME VARCHAR (100) DEFAULT NULL,
  NAME VARCHAR (50) DEFAULT NULL,
  LAST_NAME VARCHAR (50) DEFAULT NULL,
  SECOND_NAME VARCHAR (50) DEFAULT NULL,
  PHOTO VARCHAR (10) DEFAULT NULL,
  BIRTHDATE DATE DEFAULT NULL,
  POST VARCHAR (255) DEFAULT NULL,
  ADDRESS TEXT DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  LEAD_ID INT (18) DEFAULT NULL,
  EXPORT CHAR (1) DEFAULT 'N',
  TYPE_ID VARCHAR (50) DEFAULT NULL,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  PRIMARY KEY (ID),
  KEY IX_CONTACT_LAST_NAME (NAME),
  KEY IX_CONTACT_NAME (LAST_NAME),
  KEY IX_CONTACT_FULL_NAME (FULL_NAME)
);

CREATE TABLE b_crm_company
(
  ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
  DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
  DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
  CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
  MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
  ASSIGNED_BY_ID INT (1) UNSIGNED DEFAULT NULL,
  OPENED CHAR(1) DEFAULT 'N',
  TITLE varchar(255) DEFAULT NULL,
  LOGO VARCHAR (10) DEFAULT NULL,
  ADDRESS text DEFAULT NULL,
  ADDRESS_LEGAL text DEFAULT NULL,
  BANKING_DETAILS text DEFAULT NULL,
  COMMENTS text DEFAULT NULL,
  COMPANY_TYPE varchar(50) DEFAULT NULL,
  INDUSTRY varchar(50) DEFAULT NULL,
  REVENUE varchar(255) DEFAULT NULL,
  CURRENCY_ID varchar(50) DEFAULT NULL,
  EMPLOYEES varchar(50) DEFAULT NULL,
  LEAD_ID int(18) DEFAULT NULL,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  PRIMARY KEY  (ID),
  KEY IX_COMPANY_TITLE (TITLE)
);

CREATE TABLE b_crm_status
(
  ID INT (18) NOT NULL AUTO_INCREMENT,
  ENTITY_ID VARCHAR (50) NOT NULL,
  STATUS_ID VARCHAR (50) NOT NULL,
  NAME VARCHAR (100) NOT NULL,
  NAME_INIT VARCHAR (100) NULL,
  SORT INT (18) NOT NULL,
  SYSTEM CHAR (1) NOT NULL,
  PRIMARY KEY (ID),
  INDEX IX_B_CRM_STATUS (STATUS_ID, ENTITY_ID)
);

CREATE TABLE b_crm_field_multi
(
  ID int(18) NOT NULL auto_increment,
  ENTITY_ID VARCHAR (50) NOT NULL,
  ELEMENT_ID int(18) NOT NULL,
  TYPE_ID VARCHAR (50) NOT NULL,
  VALUE_TYPE VARCHAR (50) NOT NULL,
  COMPLEX_ID  VARCHAR(100) NOT NULL,
  VALUE VARCHAR (250) NOT NULL,
  PRIMARY KEY  (ID),
  KEY IX_FM_ENTITY_ELEMENT (ENTITY_ID, ELEMENT_ID)
);

CREATE TABLE b_crm_event
(
  ID int(18) NOT NULL auto_increment,
  DATE_CREATE datetime NOT NULL,
  CREATED_BY_ID int(18) NOT NULL,
  EVENT_ID varchar(50) NULL,
  EVENT_NAME varchar(255) NOT NULL,
  EVENT_TEXT_1 text NULL,
  EVENT_TEXT_2 text NULL,
  EVENT_TYPE int(11) NULL,
  FILES text NULL,
  PRIMARY KEY  (ID),
  INDEX IX_EVENT_1 (DATE_CREATE)
);

CREATE TABLE b_crm_event_relations
(
  ID int(18) NOT NULL auto_increment,
  ASSIGNED_BY_ID int(18) NOT NULL,
  ENTITY_TYPE varchar(50) NULL,
  ENTITY_ID int(11) NOT NULL,
  ENTITY_FIELD varchar(255) NULL,
  EVENT_ID int(18) NOT NULL,
  PRIMARY KEY  (ID),
  KEY IX_EVENT_REL_ENTITY (ENTITY_TYPE, ENTITY_ID, ENTITY_FIELD),
  INDEX IX_EVENT_REL_1 (EVENT_ID)
);

CREATE TABLE b_crm_entity_lock
(
  ENTITY_ID INT (11) NOT NULL,
  ENTITY_TYPE VARCHAR (10) NOT NULL,
  DATE_LOCK DATETIME DEFAULT NULL,
  LOCKED_BY VARCHAR (32) DEFAULT NULL,
  PRIMARY KEY (ENTITY_ID)
);

CREATE TABLE b_crm_entity_perms
(
  ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  ENTITY VARCHAR(20) NOT NULL,
  ENTITY_ID INT(18) NOT NULL,
  ATTR VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID),
  INDEX IX_ENTITY_ATTR (ENTITY, ENTITY_ID, ATTR)
);

CREATE TABLE b_crm_role
(
  ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE b_crm_role_perms
(
  ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  ROLE_ID INT(18) UNSIGNED NOT NULL,
  ENTITY VARCHAR(20) NOT NULL,
  FIELD VARCHAR(30) DEFAULT '-',
  FIELD_VALUE VARCHAR(255) DEFAULT NULL,
  PERM_TYPE VARCHAR(20) NOT NULL,
  ATTR CHAR(1) DEFAULT '',
  PRIMARY KEY (ID),
  INDEX IX_ROLE_ID (ROLE_ID)
);

CREATE TABLE b_crm_role_relation
(
  ID INT(18) NOT NULL AUTO_INCREMENT,
  ROLE_ID INT(18) UNSIGNED NOT NULL,
  RELATION VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  INDEX IX_ROLE_RELATION (ROLE_ID, RELATION)
);

CREATE TABLE IF NOT EXISTS b_crm_external_sale
(
	ID INT(18) NOT NULL AUTO_INCREMENT,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	DATE_CREATE datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	NAME VARCHAR(128) NULL,
	SCHEME VARCHAR(5) NOT NULL DEFAULT 'http',
	SERVER VARCHAR(192) NOT NULL,
	PORT INT(18) NOT NULL DEFAULT 80,
	LOGIN VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	MODIFICATION_LABEL INT(18) NULL,
	IMPORT_SIZE INT(18) NULL,
	IMPORT_PERIOD INT(18) NULL,
	IMPORT_PROBABILITY INT(18) NULL,
	IMPORT_RESPONSIBLE INT(18) NULL,
	IMPORT_PUBLIC char(1) NULL,
	IMPORT_PREFIX VARCHAR(128) NULL,
	IMPORT_ERRORS INT(18) NULL,
	IMPORT_GROUP_ID INT(18) NULL,
	COOKIE TEXT NULL,
	LAST_STATUS TEXT NULL,
	LAST_STATUS_DATE datetime NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_crm_catalog
(
  ID INT(1) NOT NULL,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_crm_product
(
  ID INT(1) NOT NULL,
  CATALOG_ID INT(1) NOT NULL,
  CURRENCY_ID VARCHAR(50) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL DEFAULT 0,
  ORIGINATOR_ID VARCHAR(255) NULL,
  ORIGIN_ID VARCHAR(255) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_crm_product_row
(
  ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  OWNER_ID INT(1) NOT NULL,
  OWNER_TYPE CHAR(3) NOT NULL,
  PRODUCT_ID INT(1) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL,
  PRICE_ACCOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  QUANTITY INT(1) NOT NULL,
  PRIMARY KEY(ID),
  INDEX IX_B_CRM_PROD_ROW(OWNER_ID, OWNER_TYPE, PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ASSOCIATED_ENTITY_ID INT(1),
	SUBJECT VARCHAR(512) NOT NULL,
	COMPLETED CHAR(1) NOT NULL DEFAULT 'N',
	RESPONSIBLE_ID INT(1) NOT NULL,
	PRIORITY INT(1) NOT NULL,
	NOTIFY_TYPE INT(1) NOT NULL,
	NOTIFY_VALUE INT(1) UNSIGNED,
	DESCRIPTION VARCHAR(2048),
	DESCRIPTION_TYPE TINYINT(1) UNSIGNED NULL,
	DIRECTION TINYINT(1) UNSIGNED NOT NULL,
	LOCATION VARCHAR(256),
	CREATED DATETIME NOT NULL,
	LAST_UPDATED DATETIME NOT NULL,
	START_TIME DATETIME,
	END_TIME DATETIME,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NULL,
	STORAGE_ELEMENT_IDS TEXT NULL,
	PARENT_ID INT(1) UNSIGNED NOT NULL DEFAULT 0,
	URN VARCHAR(64) NULL,
	SETTINGS TEXT NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	AUTHOR_ID INT(1) UNSIGNED NULL,
	EDITOR_ID INT(1) UNSIGNED NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT(ID, PARENT_ID, OWNER_ID, OWNER_TYPE_ID),
	INDEX IX_B_CRM_ACT_1(RESPONSIBLE_ID, COMPLETED, START_TIME)
);

CREATE TABLE IF NOT EXISTS b_crm_act_bind(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACTIVITY_ID INT(1) NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT_BIND(ACTIVITY_ID, OWNER_ID, OWNER_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act_comm(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	TYPE VARCHAR(64),
	VALUE VARCHAR(256),
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_SETTINGS TEXT,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT_COMM(ACTIVITY_ID, OWNER_ID, OWNER_TYPE_ID, ENTITY_ID, ENTITY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act_elem(
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ELEMENT_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ACTIVITY_ID, STORAGE_TYPE_ID, ELEMENT_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_usr_act(
	USER_ID INT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ACTIVITY_TIME DATETIME NOT NULL,
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	DEPARTMENT_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(USER_ID, OWNER_ID, OWNER_TYPE_ID),
	INDEX IX_B_CRM_USR_ACT(USER_ID, OWNER_ID, OWNER_TYPE_ID, ACTIVITY_TIME, ACTIVITY_ID, DEPARTMENT_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_usr_mt(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	OWNER_ID INT(1) NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	SCOPE TINYINT(1) UNSIGNED NOT NULL,
	IS_ACTIVE CHAR(1) NOT NULL DEFAULT 'N',
	TITLE VARCHAR(128),
	EMAIL_FROM VARCHAR(255),
	SUBJECT VARCHAR(255),
	BODY TEXT,
	SING_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
	SORT INT(1) NOT NULL DEFAULT 100,
	CREATED DATETIME NOT NULL,
	LAST_UPDATED DATETIME NOT NULL,
	AUTHOR_ID INT(1) UNSIGNED NOT NULL,
	EDITOR_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_USR_MT(OWNER_ID, ENTITY_TYPE_ID, SCOPE, IS_ACTIVE)
);


