CREATE TABLE b_tasks (
	ID int NOT NULL IDENTITY (1, 1),
	TITLE varchar(255) DEFAULT NULL,
	DESCRIPTION text,
	DESCRIPTION_IN_BBCODE char(1) NOT NULL DEFAULT 'N',
	PRIORITY char(1) NOT NULL DEFAULT '1',
	STATUS char(1) DEFAULT NULL,
	RESPONSIBLE_ID int DEFAULT NULL,
	DATE_START datetime DEFAULT NULL,
	DURATION_PLAN int DEFAULT NULL,
	DURATION_FACT int DEFAULT NULL,
	DURATION_TYPE varchar(5) NOT NULL DEFAULT 'days',
	REPLICATE char(1) NOT NULL DEFAULT 'N',
	DEADLINE datetime DEFAULT NULL,
	START_DATE_PLAN datetime DEFAULT NULL,
	END_DATE_PLAN datetime DEFAULT NULL,
	CREATED_BY int DEFAULT NULL,
	CREATED_DATE datetime DEFAULT NULL,
	CHANGED_BY int DEFAULT NULL,
	CHANGED_DATE datetime DEFAULT NULL,
	STATUS_CHANGED_BY int DEFAULT NULL,
	STATUS_CHANGED_DATE datetime DEFAULT NULL,
	CLOSED_BY int DEFAULT NULL,
	CLOSED_DATE datetime DEFAULT NULL,
	GUID varchar(50) DEFAULT NULL,
	XML_ID varchar(50) DEFAULT NULL,
	EXCHANGE_ID varchar(196) DEFAULT NULL,
	EXCHANGE_MODIFIED varchar(196) DEFAULT NULL,
	OUTLOOK_VERSION int DEFAULT NULL,
	MARK char(1) DEFAULT NULL,
	ALLOW_CHANGE_DEADLINE char(1) NOT NULL DEFAULT 'N',
	TASK_CONTROL char(1) NOT NULL DEFAULT 'N',
	ADD_IN_REPORT char(1) NOT NULL DEFAULT 'N',
	GROUP_ID int DEFAULT NULL,
	PARENT_ID int DEFAULT NULL,
	FORUM_TOPIC_ID int DEFAULT NULL,
	MULTITASK char(1) NOT NULL DEFAULT 'N',
	SITE_ID char(2) NOT NULL,
	DECLINE_REASON text,
	FORKED_BY_TEMPLATE_ID int DEFAULT NULL,
	CONSTRAINT b_tasks_ibpk_1 PRIMARY KEY (ID),
	CONSTRAINT b_tasks_ibfk_2 FOREIGN KEY (PARENT_ID) REFERENCES b_tasks (ID),
	CONSTRAINT b_tasks_ibfk_3 FOREIGN KEY (CREATED_BY) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_ibfk_4 FOREIGN KEY (RESPONSIBLE_ID) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_ibfk_5 FOREIGN KEY (CHANGED_BY) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_ibfk_6 FOREIGN KEY (STATUS_CHANGED_BY) REFERENCES b_user (ID)
)
GO
CREATE INDEX b_tasks_forum_topic_id_ibpk ON b_tasks(FORUM_TOPIC_ID)
GO
CREATE INDEX b_tasks_guid_ibuk ON b_tasks(GUID)
GO
CREATE TABLE b_tasks_files_temporary (
	USER_ID int NOT NULL,
	FILE_ID int NOT NULL,
	UNIX_TS int NOT NULL,
	PRIMARY KEY (FILE_ID)
)
GO
CREATE INDEX b_tasks_files_temp_uid_ibk ON b_tasks_files_temporary(USER_ID)
GO
CREATE INDEX b_tasks_files_temp_uts_ibk ON b_tasks_files_temporary(UNIX_TS)
GO
CREATE TABLE b_tasks_dependence (
	TASK_ID int NOT NULL DEFAULT '0',
	DEPENDS_ON_ID int NOT NULL DEFAULT '0',
	PRIMARY KEY (TASK_ID,DEPENDS_ON_ID),
	CONSTRAINT b_tasks_dependence_ibfk_1 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID),
	CONSTRAINT b_tasks_dependence_ibfk_2 FOREIGN KEY (DEPENDS_ON_ID) REFERENCES b_tasks (ID)
)
GO
CREATE TABLE b_tasks_file (
	TASK_ID int NOT NULL DEFAULT '0',
	FILE_ID int NOT NULL DEFAULT '0',
	PRIMARY KEY (TASK_ID,FILE_ID),
	CONSTRAINT b_tasks_file_ibfk_1 FOREIGN KEY (FILE_ID) REFERENCES b_file (ID),
	CONSTRAINT b_tasks_file_ibfk_2 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID)
)
GO
CREATE TABLE b_tasks_member (
	TASK_ID int NOT NULL DEFAULT '0',
	USER_ID int NOT NULL DEFAULT '0',
	TYPE char(1) NOT NULL DEFAULT '',
	PRIMARY KEY (TASK_ID,USER_ID,TYPE),
	CONSTRAINT b_tasks_member_ibfk_1 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID),
	CONSTRAINT b_tasks_member_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES b_user (ID)
)
GO
CREATE TABLE b_tasks_tag (
	TASK_ID int NOT NULL,
	USER_ID int NOT NULL,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY (TASK_ID,USER_ID,NAME),
	CONSTRAINT b_tasks_tag_ibfk_1 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID),
	CONSTRAINT b_tasks_tag_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES b_user (ID)
)
GO
CREATE TABLE b_tasks_template (
	ID int NOT NULL IDENTITY (1, 1),
	TASK_ID int DEFAULT NULL,
	TITLE varchar(255) DEFAULT NULL,
	DESCRIPTION text,
	DESCRIPTION_IN_BBCODE char(1) NOT NULL DEFAULT 'N',
	PRIORITY char(1) NOT NULL DEFAULT '1',
	STATUS char(1) NOT NULL DEFAULT '1',
	RESPONSIBLE_ID int DEFAULT NULL,
	DEADLINE_AFTER int DEFAULT NULL,
	REPLICATE char(1) NOT NULL DEFAULT 'N',
	REPLICATE_PARAMS text,
	CREATED_BY int DEFAULT NULL,
	XML_ID varchar(50) DEFAULT NULL,
	ALLOW_CHANGE_DEADLINE char(1) NOT NULL DEFAULT 'N',
	TASK_CONTROL char(1) NOT NULL DEFAULT 'N',
	ADD_IN_REPORT char(1) NOT NULL DEFAULT 'N',
	GROUP_ID int DEFAULT NULL,
	PARENT_ID int DEFAULT NULL,
	MULTITASK char(1) NOT NULL DEFAULT 'N',
	SITE_ID char(2) NOT NULL,
	ACCOMPLICES text,
	AUDITORS text,
	RESPONSIBLES text,
	FILES text,
	TAGS text,
	DEPENDS_ON text,
	CONSTRAINT b_tasks_template_ibpk_1 PRIMARY KEY (ID),
	CONSTRAINT b_tasks_template_ibfk_1 FOREIGN KEY (PARENT_ID) REFERENCES b_tasks (ID),
	CONSTRAINT b_tasks_template_ibfk_2 FOREIGN KEY (CREATED_BY) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_template_ibfk_3 FOREIGN KEY (RESPONSIBLE_ID) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_template_ibfk_4 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID)
)
GO
CREATE TABLE b_tasks_viewed (
	TASK_ID int NOT NULL,
	USER_ID int NOT NULL,
	VIEWED_DATE datetime NOT NULL,
	PRIMARY KEY (TASK_ID,USER_ID),
	CONSTRAINT b_tasks_viewed_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES b_user (ID),
	CONSTRAINT b_tasks_viewed_ibfk_2 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID)
)
GO
ALTER TABLE b_tasks_viewed ADD CONSTRAINT df_b_tasks_viewed_viewed_date DEFAULT GETDATE() FOR VIEWED_DATE
GO
CREATE TABLE b_tasks_log (
  CREATED_DATE datetime NOT NULL,
  USER_ID int NOT NULL,
  TASK_ID int NOT NULL,
  FIELD varchar(50) NOT NULL,
  FROM_VALUE text,
  TO_VALUE text
)
GO
CREATE TABLE b_tasks_elapsed_time (
  ID int NOT NULL IDENTITY (1, 1),
  CREATED_DATE datetime NOT NULL,
  USER_ID int NOT NULL,
  TASK_ID int NOT NULL,
  MINUTES int NOT NULL,
  COMMENT_TEXT text NULL,
  CONSTRAINT b_tasks_elapsed_time_ibpk_1 PRIMARY KEY (ID)
)
GO
ALTER TABLE b_tasks_elapsed_time ADD CONSTRAINT df_b_tasks_elapsed_time_created_date DEFAULT GETDATE() FOR CREATED_DATE
GO
CREATE INDEX b_tasks_elapsed_time_ibpk_2 ON b_tasks_elapsed_time(TASK_ID)
GO
CREATE TABLE b_tasks_reminder (
  USER_ID int NOT NULL,
  TASK_ID int NOT NULL,
  REMIND_DATE datetime NOT NULL,
  TYPE char(1) NOT NULL,
  TRANSPORT char(1) NOT NULL,
  CONSTRAINT b_tasks_reminder_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES b_user (ID),
  CONSTRAINT b_tasks_reminder_ibfk_2 FOREIGN KEY (TASK_ID) REFERENCES b_tasks (ID)
)
GO
CREATE TABLE b_tasks_filters (
	ID int NOT NULL IDENTITY (1, 1),
	USER_ID int NOT NULL,
	PARENT int NOT NULL,
	NAME varchar(255) DEFAULT NULL,
	SERIALIZED_FILTER text,
	CONSTRAINT b_tasks_filters_ibpk_1 PRIMARY KEY (ID)
)
GO
CREATE INDEX b_tasks_filters_user_id_ibpk ON b_tasks_filters(USER_ID)
