ALTER TABLE B_CRM_LEAD DROP CONSTRAINT DF_B_CRM_LEAD_DATE_MODIFY
GO
ALTER TABLE B_CRM_LEAD DROP CONSTRAINT DF_B_CRM_LEAD_OPENED
GO
ALTER TABLE B_CRM_LEAD DROP CONSTRAINT DF_B_CRM_LEAD_DATE_CREATE
GO
ALTER TABLE B_CRM_LEAD DROP CONSTRAINT PK_B_CRM_LEAD
GO
ALTER TABLE B_CRM_DEAL DROP CONSTRAINT DF_B_CRM_DEAL_DATE_MODIFY
GO
ALTER TABLE B_CRM_DEAL DROP CONSTRAINT DF_B_CRM_DEAL_OPENED
GO
ALTER TABLE B_CRM_DEAL DROP CONSTRAINT DF_B_CRM_DEAL_DATE_CREATE
GO
ALTER TABLE B_CRM_DEAL DROP CONSTRAINT DF_B_CRM_DEAL_CLOSED
GO
ALTER TABLE B_CRM_DEAL DROP CONSTRAINT PK_B_CRM_DEAL
GO
ALTER TABLE B_CRM_CONTACT DROP CONSTRAINT DF_B_CRM_CONTACT_DATE_MODIFY
GO
ALTER TABLE B_CRM_CONTACT DROP CONSTRAINT DF_B_CRM_CONTACT_OPENED
GO
ALTER TABLE B_CRM_CONTACT DROP CONSTRAINT DF_B_CRM_CONTACT_DATE_CREATE
GO
ALTER TABLE B_CRM_CONTACT DROP CONSTRAINT DF_B_CRM_CONTACT_EXPORT
GO
ALTER TABLE B_CRM_CONTACT DROP CONSTRAINT PK_B_CRM_CONTACT
GO
ALTER TABLE B_CRM_COMPANY DROP CONSTRAINT DF_B_CRM_COMPANY_DATE_MODIFY
GO
ALTER TABLE B_CRM_COMPANY DROP CONSTRAINT DF_B_CRM_COMPANY_OPENED
GO
ALTER TABLE B_CRM_COMPANY DROP CONSTRAINT DF_B_CRM_COMPANY_DATE_CREATE
GO
ALTER TABLE B_CRM_COMPANY DROP CONSTRAINT PK_B_CRM_COMPANY
GO
ALTER TABLE B_CRM_STATUS DROP CONSTRAINT PK_B_CRM_STATUS
GO
ALTER TABLE B_CRM_FIELD_MULTI DROP CONSTRAINT PK_B_CRM_FIELD_MULTI
GO
ALTER TABLE B_CRM_EVENT DROP CONSTRAINT PK_B_CRM_EVENT
GO
ALTER TABLE B_CRM_EVENT_RELATIONS DROP CONSTRAINT PK_B_CRM_EVENT_RELATIONS
GO
ALTER TABLE B_CRM_ENTITY_LOCK DROP CONSTRAINT PK_B_CRM_ENTITY_LOCK
GO
DROP TABLE B_CRM_LEAD
GO
DROP TABLE B_CRM_DEAL
GO
DROP TABLE B_CRM_CONTACT
GO
DROP TABLE B_CRM_COMPANY
GO
DROP TABLE B_CRM_STATUS
GO
DROP TABLE B_CRM_FIELD_MULTI
GO
DROP TABLE B_CRM_EVENT
GO
DROP TABLE B_CRM_EVENT_RELATIONS
GO
DROP TABLE B_CRM_ENTITY_LOCK
GO
ALTER TABLE B_CRM_ENTITY_PERMS DROP CONSTRAINT PK_B_CRM_ENTITY_PERMS
GO
DROP TABLE B_CRM_ENTITY_PERMS
GO
ALTER TABLE B_CRM_ROLE DROP CONSTRAINT PK_B_CRM_ROLE
GO
DROP TABLE B_CRM_ROLE
GO
ALTER TABLE B_CRM_ROLE_PERMS DROP CONSTRAINT PK_B_CRM_ROLE_PERMS
GO
ALTER TABLE B_CRM_ROLE_PERMS DROP CONSTRAINT DF_B_CRM_ROLE_PERMS_FIELD
GO
ALTER TABLE B_CRM_ROLE_PERMS DROP CONSTRAINT DF_B_CRM_ROLE_PERMS_FIELD_VALUE
GO
ALTER TABLE B_CRM_ROLE_PERMS DROP CONSTRAINT DF_B_CRM_ROLE_PERMS_ATTR
GO
DROP TABLE B_CRM_ROLE_PERMS
GO
ALTER TABLE B_CRM_ROLE_RELATION DROP CONSTRAINT PK_B_CRM_ROLE_RELATION
GO
DROP TABLE B_CRM_ROLE_RELATION
GO

IF OBJECT_ID(N'B_CRM_EXTERNAL_SALE', N'U') IS NOT NULL
  DROP TABLE B_CRM_EXTERNAL_SALE
GO

IF OBJECT_ID(N'B_CRM_PRODUCT_ROW', N'U') IS NOT NULL
  DROP TABLE B_CRM_PRODUCT_ROW
GO

IF OBJECT_ID(N'B_CRM_PRODUCT', N'U') IS NOT NULL
  DROP TABLE B_CRM_PRODUCT
GO

IF OBJECT_ID(N'B_CRM_CATALOG', N'U') IS NOT NULL
  DROP TABLE B_CRM_CATALOG
GO

IF OBJECT_ID(N'B_CRM_USR_ACT', N'U') IS NOT NULL
  DROP TABLE B_CRM_USR_ACT
GO

IF OBJECT_ID(N'B_CRM_ACT_ELEM', N'U') IS NOT NULL
  DROP TABLE B_CRM_ACT_ELEM
GO

IF OBJECT_ID(N'B_CRM_ACT_COMM', N'U') IS NOT NULL
  DROP TABLE B_CRM_ACT_COMM
GO

IF OBJECT_ID(N'B_CRM_ACT_BIND', N'U') IS NOT NULL
  DROP TABLE B_CRM_ACT_BIND
GO

IF OBJECT_ID(N'B_CRM_ACT', N'U') IS NOT NULL
  DROP TABLE B_CRM_ACT
GO

IF OBJECT_ID(N'B_CRM_USR_MT', N'U') IS NOT NULL
  DROP TABLE B_CRM_USR_MT
GO