DROP TABLE B_BP_WORKFLOW_TEMPLATE
GO
DROP TABLE B_BP_WORKFLOW_STATE
GO
DROP TABLE B_BP_WORKFLOW_PERMISSIONS
GO
DROP TABLE B_BP_WORKFLOW_INSTANCE
GO
DROP TABLE B_BP_TRACKING
GO
DROP TABLE B_BP_TASK
GO
DROP TABLE B_BP_TASK_USER
GO
DROP TABLE B_BP_HISTORY
GO
