CREATE TABLE b_report (
  ID int NOT NULL IDENTITY (1, 1),
  OWNER_ID varchar(20) NOT NULL,
  TITLE varchar(255) NOT NULL,
  DESCRIPTION text NULL,
  CREATED_DATE datetime NOT NULL,
  CREATED_BY int NOT NULL,
  SETTINGS text NOT NULL,
  MARK_DEFAULT smallint NULL,
  CONSTRAINT report_ibpk_1 PRIMARY KEY (ID)
)
GO

CREATE INDEX IX_REPORT_OWNER_ID ON B_REPORT (OWNER_ID)
GO