DROP TABLE B_CRM_LEAD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_LEAD
/
DROP TABLE B_CRM_DEAL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DEAL
/
DROP TABLE B_CRM_CONTACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_CONTACT
/
DROP TABLE B_CRM_COMPANY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_COMPANY
/
DROP TABLE B_CRM_STATUS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_STATUS
/
DROP TABLE B_CRM_FIELD_MULTI CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_FIELD_MULTI
/
DROP TABLE B_CRM_EVENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EVENT
/
DROP TABLE B_CRM_EVENT_RELATIONS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EVENT_RELATIONS
/
DROP TABLE B_CRM_ENTITY_LOCK CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ENTITY_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ENTITY_PERMS
/
DROP TABLE B_CRM_ROLE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE
/
DROP TABLE B_CRM_ROLE_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE_PERMS
/
DROP TABLE B_CRM_ROLE_RELATION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE_RELATION
/
DROP TABLE B_CRM_EXTERNAL_SALE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EXTERNAL_SALE
/
DROP TABLE B_CRM_PRODUCT_ROW CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_PRODUCT_ROW
/
DROP TABLE B_CRM_PRODUCT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CATALOG CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_USR_ACT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_ELEM CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_COMM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT_COMM
/
DROP TABLE B_CRM_ACT_BIND CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT_BIND
/
DROP TABLE B_CRM_ACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT
/
DROP TABLE B_CRM_USR_MT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_USR_MT
/