DROP TABLE b_tasks CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_dependence CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_file CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_member CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_tag CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_template CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_viewed CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_log CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_tasks
/
DROP SEQUENCE sq_b_tasks_template
/
DROP TABLE b_tasks_elapsed_time CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_tasks_elapsed_time
/
DROP TABLE b_tasks_reminder CASCADE CONSTRAINTS
/
DROP TABLE b_tasks_filters CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_tasks_filters
/